#INCLUDE <P16F628A.INC>
__CONFIG  _BODEN_ON & _CP_OFF & _PWRTE_ON & _WDT_OFF & _LVP_OFF & _MCLRE_ON & _HS_OSC

#DEFINE	BANK0	BCF STATUS,RP0	;Seleciona Banco 0 de memória RAM
#DEFINE	BANK1	BSF STATUS,RP0	;Seleciona Banco 1 de memória RAM
#DEFINE	btn 	1
#DEFINE	ledBtn 	0



	CBLOCK	0x20
		COUNT1
		COUNT2
		COUNT3
		AUXPORTB0
	ENDC

	ORG	0x00
	GOTO	INICIO

INICIO
	BANK1
	MOVLW	B'00000010'	
	MOVWF	TRISA
	MOVLW	B'00000000'
	MOVWF	TRISB
	MOVLW	B'00000000'
	MOVWF	INTCON	
	BANK0	
	MOVLW	B'00000111'
	MOVWF	CMCON
	CLRF	PORTB
	CLRF	COUNT3

MAIN
	BTFSS	PORTA, btn
	GOTO	btnNotPressed		; btn = 0
								; btnPressed >> PORTA, btn = 1
	BSF		PORTB, ledBtn
	GOTO	BTN_CONTINUE

btnNotPressed
	BCF		PORTB, ledBtn

BTN_CONTINUE
	INCF	COUNT1, f
	BTFSS	STATUS, Z
	GOTO	CONTINUE

	INCF	COUNT2, f
	BTFSS	STATUS, Z
	GOTO	CONTINUE
				; COUNT2 = 0
	MOVLW	.001
	BTFSS	PORTA, btn
	MOVLW	.1000
	MOVWF	COUNT2

	INCF	COUNT3, f

CONTINUE
	MOVF	PORTB, W
	ANDLW	B'00000001'
	MOVWF	AUXPORTB0
	MOVF	COUNT3, W
	ANDLW	B'11111110'
	IORWF	AUXPORTB0, W
	MOVWF	PORTB
	GOTO 	MAIN

END